# Loading the packages required to run the script. 
library(sleuth)
library(dplyr)

# Reading the table generated by kallisto.py. 
stab <- read.table("processed_data/sleuth/sleuth_input", header = TRUE, stringsAsFactors = FALSE, sep = "\t")

# Preparing the table for Sleuth LRT.
so <- sleuth_prep(stab)

# Creating a full model for Sleuth LRT.
so <- sleuth_fit(so, ~condition, "full")

# Creating an empty (null) model for Sleuth LRT. 
so <- sleuth_fit(so, ~1, "reduced")

# Running the likelihood ratio test on the two models. 
so = sleuth_lrt(so, "reduced", "full")

# Generating the tabulated results of the likelihood ratio test. 
sleuth_table = sleuth_results(so, "reduced:full", "lrt", show_all = FALSE)

# Filtering out the table so that only qvalue <= 0.05 are included, and the table is arranged by p-value. 
sleuth_significant = dplyr::filter(sleuth_table, qval <= 0.05) |> dplyr::arrange(pval)

# Choosing only the columns (variables) that we want to print to the log file. 
sig_sleuth <- sleuth_significant |>  select(target_id, test_stat, pval, qval)

# Writing the results to a file. 
write.table(sig_sleuth, file = "processed_data/sleuth/sleuth_output", quote = FALSE, row.names = FALSE)